# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /autofs/nccs-svm1_sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd/bin/cmake

# The command to remove a file.
RM = /autofs/nccs-svm1_sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /lustre/orion/gen150/world-shared/abby-summer24/gunrock_hip_develop/gunrock-hip-develop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /lustre/orion/gen150/world-shared/abby-summer24/gunrock_hip_develop/gunrock-hip-develop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/autofs/nccs-svm1_sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/autofs/nccs-svm1_sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /lustre/orion/gen150/world-shared/abby-summer24/gunrock_hip_develop/gunrock-hip-develop/CMakeFiles /lustre/orion/gen150/world-shared/abby-summer24/gunrock_hip_develop/gunrock-hip-develop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /lustre/orion/gen150/world-shared/abby-summer24/gunrock_hip_develop/gunrock-hip-develop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sssp

# Build rule for target.
sssp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sssp
.PHONY : sssp

# fast build rule for target.
sssp/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/sssp/CMakeFiles/sssp.dir/build.make examples/algorithms/sssp/CMakeFiles/sssp.dir/build
.PHONY : sssp/fast

#=============================================================================
# Target rules for targets named bfs

# Build rule for target.
bfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfs
.PHONY : bfs

# fast build rule for target.
bfs/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/bfs/CMakeFiles/bfs.dir/build.make examples/algorithms/bfs/CMakeFiles/bfs.dir/build
.PHONY : bfs/fast

#=============================================================================
# Target rules for targets named color

# Build rule for target.
color: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 color
.PHONY : color

# fast build rule for target.
color/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/color/CMakeFiles/color.dir/build.make examples/algorithms/color/CMakeFiles/color.dir/build
.PHONY : color/fast

#=============================================================================
# Target rules for targets named geo

# Build rule for target.
geo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geo
.PHONY : geo

# fast build rule for target.
geo/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/geo/CMakeFiles/geo.dir/build.make examples/algorithms/geo/CMakeFiles/geo.dir/build
.PHONY : geo/fast

#=============================================================================
# Target rules for targets named pr

# Build rule for target.
pr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pr
.PHONY : pr

# fast build rule for target.
pr/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/pr/CMakeFiles/pr.dir/build.make examples/algorithms/pr/CMakeFiles/pr.dir/build
.PHONY : pr/fast

#=============================================================================
# Target rules for targets named ppr

# Build rule for target.
ppr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ppr
.PHONY : ppr

# fast build rule for target.
ppr/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/ppr/CMakeFiles/ppr.dir/build.make examples/algorithms/ppr/CMakeFiles/ppr.dir/build
.PHONY : ppr/fast

#=============================================================================
# Target rules for targets named bc

# Build rule for target.
bc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bc
.PHONY : bc

# fast build rule for target.
bc/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/bc/CMakeFiles/bc.dir/build.make examples/algorithms/bc/CMakeFiles/bc.dir/build
.PHONY : bc/fast

#=============================================================================
# Target rules for targets named hits

# Build rule for target.
hits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hits
.PHONY : hits

# fast build rule for target.
hits/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/hits/CMakeFiles/hits.dir/build.make examples/algorithms/hits/CMakeFiles/hits.dir/build
.PHONY : hits/fast

#=============================================================================
# Target rules for targets named kcore

# Build rule for target.
kcore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kcore
.PHONY : kcore

# fast build rule for target.
kcore/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/kcore/CMakeFiles/kcore.dir/build.make examples/algorithms/kcore/CMakeFiles/kcore.dir/build
.PHONY : kcore/fast

#=============================================================================
# Target rules for targets named spmv

# Build rule for target.
spmv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spmv
.PHONY : spmv

# fast build rule for target.
spmv/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/spmv/CMakeFiles/spmv.dir/build.make examples/algorithms/spmv/CMakeFiles/spmv.dir/build
.PHONY : spmv/fast

#=============================================================================
# Target rules for targets named spgemm

# Build rule for target.
spgemm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spgemm
.PHONY : spgemm

# fast build rule for target.
spgemm/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/spgemm/CMakeFiles/spgemm.dir/build.make examples/algorithms/spgemm/CMakeFiles/spgemm.dir/build
.PHONY : spgemm/fast

#=============================================================================
# Target rules for targets named mst

# Build rule for target.
mst: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mst
.PHONY : mst

# fast build rule for target.
mst/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/mst/CMakeFiles/mst.dir/build.make examples/algorithms/mst/CMakeFiles/mst.dir/build
.PHONY : mst/fast

#=============================================================================
# Target rules for targets named tc

# Build rule for target.
tc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tc
.PHONY : tc

# fast build rule for target.
tc/fast:
	$(MAKE) $(MAKESILENT) -f examples/algorithms/tc/CMakeFiles/tc.dir/build.make examples/algorithms/tc/CMakeFiles/tc.dir/build
.PHONY : tc/fast

#=============================================================================
# Target rules for targets named cmd

# Build rule for target.
cmd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmd
.PHONY : cmd

# fast build rule for target.
cmd/fast:
	$(MAKE) $(MAKESILENT) -f examples/tools/CMakeFiles/cmd.dir/build.make examples/tools/CMakeFiles/cmd.dir/build
.PHONY : cmd/fast

#=============================================================================
# Target rules for targets named csr_binary

# Build rule for target.
csr_binary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csr_binary
.PHONY : csr_binary

# fast build rule for target.
csr_binary/fast:
	$(MAKE) $(MAKESILENT) -f examples/tools/CMakeFiles/csr_binary.dir/build.make examples/tools/CMakeFiles/csr_binary.dir/build
.PHONY : csr_binary/fast

#=============================================================================
# Target rules for targets named nearest_neighbor

# Build rule for target.
nearest_neighbor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nearest_neighbor
.PHONY : nearest_neighbor

# fast build rule for target.
nearest_neighbor/fast:
	$(MAKE) $(MAKESILENT) -f examples/tools/CMakeFiles/nearest_neighbor.dir/build.make examples/tools/CMakeFiles/nearest_neighbor.dir/build
.PHONY : nearest_neighbor/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bc"
	@echo "... bfs"
	@echo "... cmd"
	@echo "... color"
	@echo "... csr_binary"
	@echo "... geo"
	@echo "... hits"
	@echo "... kcore"
	@echo "... mst"
	@echo "... nearest_neighbor"
	@echo "... ppr"
	@echo "... pr"
	@echo "... spgemm"
	@echo "... spmv"
	@echo "... sssp"
	@echo "... tc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

